services:
  bot1:
    build: ./bot
    networks:
      victim_net:
        ipv4_address: 172.30.0.4
    container_name: bot
    cap_add:
      - NET_RAW

  bot2:
    build: ./bot2
    networks:
      victim_net:
        ipv4_address: 172.30.0.5
    container_name: bot2

  bot3:
    build: ./bot3
    networks:
      victim_net:
        ipv4_address: 172.30.0.6
    container_name: bot3

  bot4:
    build: ./bot4
    networks:
      victim_net:
        ipv4_address: 172.30.0.7
    container_name: bot4

  # victim-web:
  #   build: ./victim-web
  #   networks:
  #     victim_net:
  #       ipv4_address: 172.30.0.2
  #   container_name: victim-web
  #   ports:
  #     - "3000:3000"

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     demo_net:
  #       ipv4_address: 172.30.0.3

networks:
  victim_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
